### ISSUE TITLE
DataTable tied to LDAvis

### ISSUE THREAD

**Issue by swayson** [cpsievert/LDAvis#45]
Hi there,

I am fairly new to WebDev side of things. I am using Shiny and LDAvis but would like to also add a basic DataTable. Such as this one: http://shiny.rstudio.com/gallery/basic-datatable.html

In addition, I would like to have the DataTable bound to LDAvis, such that if I select a topic, then the table will filter to the respective documents. 

Is this possible with the LDAvis as it stands at the moment? Could someone please point my in the direction or provide resources as to what I may need to consider in doing so? 

Many thanks

**Comment by cpsievert** [comment]
Unfortunately it isn't very straightforward to access the currently selected topic in a shiny app. 

That being said, it's important to note that DataTables does not depend on shiny -> http://rstudio.github.io/DT/

Unless you are comfortable with JavaScript, it's going to be hard to link the table to the viz. It'd be much, much easier to rely on the search option that comes for free with DataTable to filter to a topic of interest.

**Comment by crew102** [comment]
Can't we just stash calls to `Shiny.onInputChange()` inside the relevant LDAvis functions (e.g., `topic_on`, `term_hover`, etc)?. For example, If I add `Shiny.onInputChange('ldavis_topic_sel', vis_state.topic);`, I can get access to the current selected topic at `input$ldavis_topic_sel` :

```r
library(LDAvis)
library(shiny)

ui <- shinyUI(
  fluidPage(
    sliderInput("nTerms", "Number of terms to display", min = 20, max = 40, value = 30),
    visOutput('myChart')
  )
)

server <- shinyServer(function(input, output, session) {
  
  output$myChart <- renderVis({
    with(
      TwentyNewsgroups, 
      createJSON(phi, theta, doc.length, vocab, term.frequency, R = input$nTerms)
    )
  })
  
  observe({
    if (is.null(input$ldavis_topic_sel)) return()
    print(input$ldavis_topic_sel)
  })
})

shinyApp(ui, server)
```

**Comment by cpsievert** [comment]
@crew102 yea, happy to consider a PR, thanks!

**Comment by crew102** [comment]
Hey @cpsievert, quick question. I'd like to link the LDAvis output to four shiny inputs: term click, term hover, topic click, and topic hover. I think we need both hover and click events because the user may want to link the LDAvis output to a heavy operation on the server side (i.e., filtering a large data table for documents containing the clicked term), which they may want to only run on a click event. Since I want to add inputs for click events, I think it's important that it's clear from the LDAvis output when a click has happened. For this reason I'd like to change the color of a clicked term to be red, as well as increase the stroke width of a clicked topic (i.e., a clicked circle). See below for example. Is this cool with you?

![asdf](https://user-images.githubusercontent.com/11220793/39005686-dc0eb1ee-43ce-11e8-8494-1978b4525972.PNG)
