### ISSUE TITLE
Recipe for embedding in static page with knitr?

### ISSUE THREAD

**Issue by elbamos** [cpsievert/LDAvis#48]
It looks like it should be possible to embed an lda visualization in a self-contained HTML5, by using knitr and an iframe of some sort.  Do you have a recipe for doing so?

Thanks much!

**Comment by kshirley** [comment]
Hi,

Carson will probably know more about smooth integration with `knitr`, etc.

But if you simply want to embed an "instance" of `LDAvis` into a webpage, you can create the .json file for your data using the `createJSON()` function, save it as, say, "data.json", and then create an empty div in your webpage called "mydiv" and insert as follows:

`<div id = "mydiv"></div>`
`<script>`
`var vis = new LDAvis("#mydiv", "data.json");`
`</script>`

This will populate `mydiv

**Comment by elbamos** [comment]
That's actually exactly what I tried.  Well, in knitr, I called serVis() to write to a directory, the embedded an iframe with:  

```{r}
serVis(json, out.dir = 'vis', open.browser=FALSE)
```
<iframe width="500" height="500" src="vis/index.html" frameborder="0"></iframe>

And I get the blank frame but, no visualization.  I expect this has something to do with javascript and file locations.

**Comment by elbamos** [comment]
Oops!  Looks like the comments are interpreting markdown and html... anyway, well, there was an iframe tag after that serVis :p

**Comment by kshirley** [comment]
You could try to debug your page using the javascript debugger in your browser's development tools. Or by studying the source code of the page.

Without more info, I don't think I'm going to be able to figure out exactly what's going on. If it's any help, the working example that I referred to above is here:

http://www.research.att.com/~kshirley/LDAvis/

It doesn't use an iframe, so maybe your problem is related to the iframe? Most of the time when I have issues like these I resort to trial-and-error to solve the problem, to be honest.

Please comment again if you get it working, or if you have a suggestion for a smooth pipeline that we can help implement in the package.

**Comment by elbamos** [comment]
Thanks Kenny - it works!  Looks like some chrome plugin or something was blocking the js from running locally.

**Comment by kshirley** [comment]
Ah, great! Glad it's working.

-k

**Comment by him4u324** [comment]
I am also trying to embed LDAvis output to Rmarkdown and share the html output just like any other rmarkdown output with intact interactivity. Can you please help.

**Comment by samdhu1116** [comment]
I am too trying to embed LDAvis output to Rmarkdown and share the html output just like any other rmarkdown output with intact interactivity. Can you please help.
