### ISSUE TITLE
Text in final visualization in different language than english

### ISSUE THREAD

**Issue by MarcinKosinski** [cpsievert/LDAvis#60]
I could provide polish version of LDAvis. We could add additional parameter: `output.language` to createJSON. If this is OK I can prepare pull request, but I need to know whether you are reading comments on this repo and whether such proposition is OK for you and in the future will be submitted to CRAN ?

**Comment by cpsievert** [comment]
If it isn't overly complicated to add support, I'll definitely consider, thanks!

**Comment by kshirley** [comment]
Hey Marcin,

I agree with Carson, this sounds useful. We are reading comments on this repo (although our time has been limited lately).

Could you describe in a couple sentences what you have in mind? Is there a certain set of languages that would become supported by your added feature?

thanks!
k

**Comment by MarcinKosinski** [comment]
Hi,

In the `serVis()` function you are copying `system.file("htmljs", package = "LDAvis")` directory to the desired folder in which the final visualization will be stored https://github.com/cpsievert/LDAvis/blob/master/R/serVis.R#L40

In this step you copy such files: 

````{R}
> list.files(system.file("htmljs", package = "LDAvis"))
[1] "d3.v3.js"   "index.html" "lda.css"    "ldavis.js" 
````

In `ldavis.js` you have got text that is set in english (example: https://github.com/cpsievert/LDAvis/blob/master/inst/htmljs/ldavis.js#L481)

I could provide a PR with `pl-ldavis.js` file that would have polish text to be added to visualization.
Then in `serVis` we could add additional parameter `language` that would copy `pl-ldavis.js` instead of `ldavis.js` and would substitue  line 7 in `index.html` from
https://github.com/cpsievert/LDAvis/blob/master/inst/htmljs/index.html#L7

````{R}
 <script src="ldavis.js"></script>
```

to


````{R}
 <script src="pl-ldavis.js"></script>
```

**Comment by kshirley** [comment]
Ah, I see! First, I have a confession to make: I thought when you wrote "polish text" that you were referring to some new software library called "polish" that would support multiple languages, or something like that. I didn't realize you were referring to the *Polish* language, as in "how people talk in Poland" ! :)

I think the idea sounds fine, and thanks for the very clear summary.

It might not have a large impact, since it's only adding support for one additional language (there were some earlier requests regarding support of Chinese characters, so I was thinking maybe we could kill multiple birds with one stone here), but there's basically no downside that I can see provided that:

1. the file "pl-ldavis.js" is not a huge file (so that it doesn't bloat the package size).

2. in the new version of `serVis()` we set the default language to English so that we don't break any existing scripts.

So I say it sounds fine - and thanks!

Carson, what do you think? Also, a question for you, Carson: is this an opportunity to add a couple simple unit tests to the package, in anticipation of making future pull requests easier to check?

-kenny

**Comment by cpsievert** [comment]
> is this an opportunity to add a couple simple unit tests to the package

sure, unit tests are always a good idea, but I don't have much time to write/review them right now

**Comment by MarcinKosinski** [comment]
Hi again,

I've provided PR for this feature here https://github.com/cpsievert/LDAvis/pull/62
